#!/usr/bin/env bash
# display subdomains information

check_subdomain_info () {
        record_type="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
        ip_address="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
        echo "The subdomain $2 is a $record_type record and points to $ip_address"
}

if [ "$#" == 2 ]
then
        check_subdomain_info "$1" "$2"
elif [ "$#" == 1 ]
then
        for subdomain in www lb-01 web-01 web-02
        do
                check_subdomain_info "$1" "$subdomain"
        done
fi
