#!/usr/bin/env bash
# a script to install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chmod -R 755 /var/www
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
