#!/usr/bin/env bash
# a script to install nginx web server
sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
