#!/usr/bin/env bash
# a script to custom 404 page
#sudo apt-get update -y
#sudo apt-get install -y nginx
#sudo chown -R "$USER":"$USER" /var/www/html
#echo "Hello World!" > /var/www/html/index.html
#sudo sed -i '/listen \[::\]:80 default_server;/a rewrite ^/redirect_me/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
# sudo sed -i '/server_name _;/a error_page 404 /404.html; location = /404.html {root /usr/share/nginx/html; internal;}' /etc/nginx/sites-available/default
#sudo service nginx restart
#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

sudo sh -c 'echo "Hello World" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/listen \[::\]:80 default_server;/a rewrite ^/redirect_me/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i '/listen \[::\]:80 default_server;/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html; internal;}' /etc/nginx/sites-available/default

sudo service nginx restart
