#!/usr/bin/env bash
# This script is displaying the file content of /etc/passwd using while + IFS
filename='/etc/passwd'
while IFS=':' read -r username password uid gid userinfo home shell
do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < $filename
