#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, and add "Hi" for 9th iteration
i=1
while [ $i -lt 10 ]
do
	echo "Best School"
	if [ $i == 9 ]
	then
		echo "Hi"
		echo "Best School"
	fi
	((i++))
done
