#!/usr/bin/env bash
# This script is displaying "Best School" except "bad luck" for 4th loop and "good luck" for 8th loop
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
