#!/usr/bin/env bash
# This script is displaying 1 to 20.
# showing 4 and "bad luck from China" for 4th loop
# showing 9 and "bad luck from Japan" for 9th loop
# showing 17 and "bad luck from Italy" for 17th loop
i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo $i
			echo "bad luck from China"
			;;
		9)
			echo $i
			echo "bad luck from Japan"
			;;
		17)
			echo $i
			echo "bad luck from Italy"
			;;
		*)
			echo $i
			;;
	esac
	((i++))
done

